### ISSUE TITLE
tvdb_client not working on MacOs python3.5

### ISSUE THREAD

**Issue by thilux** [thilux/tvdb_client#1]
When trying to import the tvdb_client on a MacOS machine with python3.5, the following error is raised:

`Thiagos-MacBook-Pro:~ tsantana$ python3.5
Python 3.5.1 (default, Apr 18 2016, 11:46:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tvdb_client import ApiV2Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/tvdb_client-0.1.1-py3.5.egg/tvdb_client/__init__.py", line 2, in <module>
    from .clients import ApiV1Client, ApiV2Client
  File "/usr/local/lib/python3.5/site-packages/tvdb_client-0.1.1-py3.5.egg/tvdb_client/clients/__init__.py", line 1, in <module>
    from .ApiV1Client import ApiV1Client
  File "/usr/local/lib/python3.5/site-packages/tvdb_client-0.1.1-py3.5.egg/tvdb_client/clients/ApiV1Client.py", line 2, in <module>

    from shared import BaseClient
ImportError: No module named 'shared'`

This needs to be fixed so that the API can be used on python3 correctly.

**Comment by thilux** [comment]
It has been identified that this issue is caused by Python3 relative imports changes when compared to python2.
